config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :blogs do
    resources :comments, only: [:new ,:create, :edit, :update, :destroy]
  end
  resources :courses
  resources :courses do
    resources :qualifications
    resources :content_courses, only: [:new ,:create, :edit, :update, :destroy]
    resources :asignar_estudiantes
  end
  resources :course_users
  resources :reports
  get 'home/index'
  resources :activate_user

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  	validates :title, :content, presence: true
	validates :title, length: { in: 1..75 , message: "debe tener entre 1 y 75 caracteres"}
	validates :content, length: { in: 1..10000 , message: "debe tener entre 1 y 10000 caracteres"}
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    user = User.find(current_user.id)
    @blog = user.blogs.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      user = User.find(current_user.id)
      @blog = user.blogs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :content)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :user_id ,class: "hidden "%>

  <div class="form-group label-floating">
    <%= f.label :Título, :class => "control-label" %><br>
    <%= f.text_field :title, autofocus: true, :class => "form-control" %>
  </div>

  <div class="form-group label-floating">
    <%= f.label :Contenido, :class => "control-label" %><br>
    <%= f.text_area :content, :class => "tinymce", :rows => 5, :cols => 50 %>
    <%= tinymce %>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <div class="actions">
        <%= f.submit "Guardar", :class => "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Editar Blog</h2>
                    </div>

                    <div class="card-content table-responsive">
                        <%= render 'form', blog: @blog %>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/blogs/index.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Blogs</h2>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table">
                            <thead class="text-primary titulo">
                              <th>Creador</th>
                              <th>Titulo</th>
                              <th>Ver</th>                          
                              <th>Editar</th>
                              <th>Eliminar</th>
                            </thead>
                            <tbody>
                            <% @blogs.each do |blog| %>
                                <tr id="<%=blog.id%>">
                                  <td><%= blog.user.name %></td>
                                  <td><%= blog.title %></td>
                                  <td align="left"><%= link_to blog do %>
                                      <%= fa_icon "search-plus lg" %>
                                    <%end%>
                                  </td>
                                  <%if current_user.rol==1 || current_user.id==blog.user.id %>
                                    <td align="left"><%= link_to edit_blog_path(blog) do%>
                                        <%= fa_icon "pencil-square-o lg"%>                                        
                                      <%end%>
                                    </td>
                                    <td align="left"><%= link_to blog, method: :delete, data: { confirm: 'Está seguro?' } do%>
                                        <%= fa_icon "trash lg"%>                                        
                                      <%end%>
                                    </td>
                                  <%end%>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/blogs/new.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Nuevo Blog</h2>
                    </div>

                    <div class="card-content table-responsive">
                        <%= render 'form', blog: @blog %>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/blogs/show.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Blog</h2>
                    </div>                    
                    <div class="card-content table-responsive">                     
                        <div class="row">
                            <div class="col-md-12">
                              <h3 align="center"> <%= @blog.title %> </h3>
                            </div>
                            <div class="col-md-4 col-md-offset-2">                                                      
                            </div>
                        </div>
                      <%= @blog.content.html_safe %> 
                      <br>
                      <div class="row">                              
                        <div class="col-md-3 col-md-offset-1">
                          <%= link_to new_blog_comment_path(@blog) , class: "btn btn-danger btn-block" do%>
                          <%= fa_icon "commenting"%>
                            Comentar
                          <%end%>
                        </div>
                        <div class="col-md-7">
                          <br>
                          <br>
                          <p align="right"> Creado por: <%= @blog.user.name %></p>
                        </div>                                
                      </div>
                      

                        <% @blog.comments.each do |comment| %>
                          <div class="card">
                            <div class="card-content">
                              <div class="row">
                                <div class="col-md-6">
                                  <h4> <%= comment.user.name %> comentó: </h4>
                                </div>                                
                              </div>
                              <%= comment.content.html_safe %>                             
                            </div>
                            <%if current_user.rol==1 || current_user.id==comment.user.id %>
                              <div class="card_footer">
                                <div class="row">                              
                                  <div class="col-md-5 col-md-offset-1">
                                    <%= link_to edit_blog_comment_path(@blog,comment), class: "btn btn-default btn-block" do%>
                                      <%= fa_icon "pencil-square-o"%>
                                        Editar Comentario                                        
                                      <%end%>
                                  </div> 
                                  <div class="col-md-5"> 
                                    <%= link_to [@blog,comment], method: :delete, data: { confirm: 'Esta Seguro??' } ,class: "btn btn-default btn-block" do%>
                                      <%= fa_icon "trash"%> 
                                        Eliminar Comentario                                       
                                      <%end%>
                                  </div>                              
                                </div>                                       
                              </div>
                            <%end%>
                          </div>
                         <% end %>                 
                    </div>                  
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>