config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :blogs do
    resources :comments, only: [:new ,:create, :edit, :update, :destroy]
  end
  resources :courses
  resources :courses do
    resources :qualifications
    resources :content_courses, only: [:new ,:create, :edit, :update, :destroy]
    resources :asignar_estudiantes
  end
  resources :course_users
  resources :reports
  get 'home/index'
  resources :activate_user

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  	validates :content, presence: true
	validates :content, length: { in: 1..5000, message: "debe tener entre 1 y 5.000 caracteres"}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    blog = Blog.find(params[:blog_id])
    user = User.find(current_user.id)
    @comment = blog.comments.build(:user => user)
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to  @comment.blog, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.blog, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to Blog.find(params[:blog_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      blog = Blog.find(params[:blog_id])
      @comment = blog.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :blog_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([comment.blog,comment]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :user_id ,class: "hidden"%>
  <%= f.text_field :blog_id,class: "hidden" %>

  <div class="form-group label-floating">
    <%= f.label :content, :class => "control-label" %><br>
    <%= f.text_area :content, :class => "tinymce", :rows => 5, :cols => 50 %>
    <%= tinymce %>
  </div>
  
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <div class="actions">
        <%= f.submit "Guardar", :class => "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Editar Comentario</h2>
                    </div>

                    <div class="card-content table-responsive">
                        <%= render 'form', comment: @comment %>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Blog</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.blog %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_blog_comment_path(params[:blog_id]) %>

app/views/comments/new.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">Nuevo Comentario</h2>
                    </div>

                    <div class="card-content table-responsive">
                        <%= render 'form', comment: @comment %>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @comment.blog %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>