config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :blogs do
    resources :comments, only: [:new ,:create, :edit, :update, :destroy]
  end
  resources :courses
  resources :courses do
    resources :qualifications
    resources :content_courses, only: [:new ,:create, :edit, :update, :destroy]
    resources :asignar_estudiantes
  end
  resources :course_users
  resources :reports
  get 'home/index'
  resources :activate_user

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :verificar_curso, only: [:edit, :show, :update]
  before_action :curso_activo?, only: [:edit,:update]
  respond_to :html

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @profesores = User.where(rol: 2)
    @course = Course.new
    respond_with(@course, @profesores)
  end

  # GET /courses/1/edit
  def edit
    @profesores = User.where( rol: 2)
    respond_with( @profesores)
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :date_end, :user_id, :active, :description, :code )
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group label-floating"><br />
    <%= f.label :name, :class => "control-label" %>
    <%= f.text_field :name, autofocus: true, :class => "form-control" %>
  </div>

  <div class="form-group label-floating"><br />
    <%= f.label :Código, :class => "control-label" %>
    <%= f.text_field :code, autofocus: true, :class => "form-control" %>
  </div>

  <div class="form-group label-floating">
    <%= f.label :Descripción, :class => "control-label"%><br />
    <%= f.text_area :description, autofocus: true,  :class => "form-control"%>
  </div>

  <div class="form-group label-floating">
    <%= f.label :profesor, :class => "control-label" %><br />
    <%= f.select :user_id, @profesores.map{|p| [p.name, p.id]}, {}, {class: "form-control"} %>
  </div>

  <div class="form-group label-floating">
    <%= f.label :Fecha_Finalización_De_Curso, :class => "control-label" %><br />
    <%= f.date_field :date_end, autofocus: true, :class => "form-control" %>
  </div>

  <div class="form-group label-floating">
    <%= f.label :estado ,:class => "control-label"%><br />
    <%= f.select :active, [['Activado', true], ['Desactivado', false]], {}, {class: "form-control"} %>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="actions">
        <%= f.submit "Guardar", :class => "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
	<div class="row">
	  <div class=" col-md-offset-4  col-sm-offset-4  col-xs-offset-1">
	    <div class="card caja ">
	      <div class="card-header" data-background-color="red">
	      <div class="col-md-3 col-sm-3 col-xs-2">
	        <div class="cajon">
	         <%= image_tag "uni.png", :alt => "univalle +", :title => "univalle", :class => " imagen"%>
	        </div>
	        </div> 
	        <div class="col-md-9 col-sm-9 col-xs-8">
	        <div class="text-center">
	          <h2 class="texto">Editar Curso</h2>
	        </div>
	        </div> 
	      </div>
	      <div class="card-content">

				<%= render 'form', course: @course %>
	      </div>
	    </div>
	</div>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/courses/index.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">CURSOS</h2>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table">
                            <thead class="text-primary titulo">
                              <th>Nombre</th>
                              <th>Código</th>
                              <th>Estado</th>
                              <th>Editar</th>
                              <th>Eliminar</th>
                            </thead>
                            <tbody>
                            <% @courses.each do |course| %>
                                <tr id="<%=course.id%>">
                                  <td class="text-primary " ><%= link_to course.name, course %></td>
                                  <td><%= course.code%></td>
                                  <%if course.active %>
                                    <td> Curso Activo </td> 
                                  <%else%>
                                    <td> Curso Inactivo </td> 
                                  <%end%>
                                  <td align="left"><%= link_to edit_course_path(course) do %> 
                                      <%= fa_icon "pencil lg"%>                                        
                                      <%end%>
                                  </td>
                                  <td align="left"><%= link_to course, method: :delete, data: { confirm: 'Está seguro?'} do%>
                                    <%= fa_icon "trash lg"%>                                        
                                      <%end%>
                                  </td>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>

app/views/courses/new.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
	<div class="row">
	  <div class=" col-md-offset-4  col-sm-offset-4  col-xs-offset-1">
	    <div class="card caja ">
	      <div class="card-header" data-background-color="red">
	      <div class="col-md-3 col-sm-3 col-xs-2">
	        <div class="cajon">
	         <%= image_tag "uni.png", :alt => "univalle +", :title => "univalle", :class => " imagen"%>
	        </div>
	        </div> 
	        <div class="col-md-9 col-sm-9 col-xs-8">
	        <div class="text-center">
	          <h2 class="texto">Crear Curso</h2>
	        </div>
	        </div> 
	      </div>
	      <div class="card-content">
	          	<%= render 'form', course: @course %>
	      </div>
	    </div>
	</div>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/courses/show.html.erb
<%= render "layouts/menu" %>
<div class="content">
  <div class="container-fluid">   
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center" data-background-color="red">
                        <br>
                        <h2 class="title titulo ">CURSO</h2>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table">
                            <thead class="text-primary titulo">
                              <th>Nombre</th>
                              <th>Código</th>
                              <th>Fecha Finalización de Curso</th>
                              <th>Descripción</th>
                              <th>Estado</th>
                              <th>Profesor</th>
                              <th></th>
                            </thead>
                            <tbody>
                                <tr id="<%=@course.id%>">
                                  <td class="text-primary " ><%= @course.name%></td>
                                  <td><%= @course.code%></td>
                                  <td><%= @course.date_end %></td>
                                   <td><%= @course.description %></td>
                                  <% if  @course.active %>
                                    <td> Curso Activo</td>
                                  <% else %>
                                    <td> Curso Inactivo</td>
                                  <% end %>
                                  <td><%= @course.user.name%></td>
                                  <td><%=image_tag @course.user.avatar.url(:peque) %></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <%= link_to "Asignar estudiantes", new_course_asignar_estudiante_path(@course), class: "btn btn-danger" %>
            </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>