config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :blogs do
    resources :comments, only: [:new ,:create, :edit, :update, :destroy]
  end
  resources :courses
  resources :courses do
    resources :qualifications
    resources :content_courses, only: [:new ,:create, :edit, :update, :destroy]
    resources :asignar_estudiantes
  end
  resources :course_users
  resources :reports
  get 'home/index'
  resources :activate_user

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/views/layouts/_footer.html.erb
			
<%= javascript_tag do %>
	$(document).ready(function() {
	    if ($( "#notice" ).length) {
	        demo.showNotification('bottom','right',$("#notice").text(),2)
	    }
	    if ($( "#alert" ).length) {
	        demo.showNotification('bottom','right',$("#alert").text(),1)
	    }
});


var searchVisible = 0;
var transparent = true;

var transparentDemo = true;
var fixedTop = false;

var mobile_menu_visible = 0,
    mobile_menu_initialized = false,
    toggle_initialized = false,
    bootstrap_nav_initialized = false;

var seq = 0, delays = 80, durations = 500;
var seq2 = 0, delays2 = 80, durations2 = 500;


$(document).ready(function(){

    $sidebar = $('.sidebar');

    $.material.init();

    md.initSidebarsCheck();

    window_width = $(window).width();

    // check if there is an image set for the sidebar's background
    md.checkSidebarImage();

    //  Activate the tooltips
    $('[rel="tooltip"]').tooltip();


    $('.form-control').on("focus", function(){
        $(this).parent('.input-group').addClass("input-group-focus");
    }).on("blur", function(){
        $(this).parent(".input-group").removeClass("input-group-focus");
    });

});

// activate collapse right menu when the windows is resized
$(window).resize(function(){
    md.initSidebarsCheck();

    // reset the seq for charts drawing animations
    seq = seq2 = 0;

});

md = {
    misc:{
        navbar_menu_visible: 0,
        active_collapse: true,
        disabled_collapse_init: 0,
    },

    checkSidebarImage: function(){
        $sidebar = $('.sidebar');
        image_src = $sidebar.data('image');

        if(image_src !== undefined){
            sidebar_container = '<div class="sidebar-background" style="background-image: url(' + image_src + ') "/>'
            $sidebar.append(sidebar_container);
        }
    },

    initSidebarsCheck: function(){
        if($(window).width() <= 991){
            if($sidebar.length != 0){
                md.initRightMenu();

            } else {
                md.initBootstrapNavbarMenu();
            }
        }

    },

    checkScrollForTransparentNavbar: debounce(function() {
            if($(document).scrollTop() > 260 ) {
                if(transparent) {
                    transparent = false;
                    $('.navbar-color-on-scroll').removeClass('navbar-transparent');
                }
            } else {
                if( !transparent ) {
                    transparent = true;
                    $('.navbar-color-on-scroll').addClass('navbar-transparent');
                }
            }
    }, 17),


    initRightMenu: debounce(function(){
        $sidebar_wrapper = $('.sidebar-wrapper');

        if(!mobile_menu_initialized){
            $navbar = $('nav').find('.navbar-collapse').first().clone(true);

            nav_content = '';
            mobile_menu_content = '';

            $navbar.children('ul').each(function(){

                content_buff = $(this).html();
                nav_content = nav_content + content_buff;
            });

            nav_content = '<ul class="nav nav-mobile-menu">' + nav_content + '</ul>';

            $navbar_form = $('nav').find('.navbar-form').clone(true);

            $sidebar_nav = $sidebar_wrapper.find(' > .nav');

            // insert the navbar form before the sidebar list
            $nav_content = $(nav_content);
            $nav_content.insertBefore($sidebar_nav);
            $navbar_form.insertBefore($nav_content);

            $(".sidebar-wrapper .dropdown .dropdown-menu > li > a").click(function(event) {
                event.stopPropagation();

            });

            mobile_menu_initialized = true;
        } else {
            if($(window).width() > 991){
                // reset all the additions that we made for the sidebar wrapper only if the screen is bigger than 991px
                $sidebar_wrapper.find('.navbar-form').remove();
                $sidebar_wrapper.find('.nav-mobile-menu').remove();

                mobile_menu_initialized = false;
            }
        }

        if(!toggle_initialized){
            $toggle = $('.navbar-toggle');

            $toggle.click(function (){

                if(mobile_menu_visible == 1) {
                    $('html').removeClass('nav-open');

                    $('.close-layer').remove();
                    setTimeout(function(){
                        $toggle.removeClass('toggled');
                    }, 400);

                    mobile_menu_visible = 0;
                } else {
                    setTimeout(function(){
                        $toggle.addClass('toggled');
                    }, 430);


                    main_panel_height = $('.main-panel')[0].scrollHeight;
                    $layer = $('<div class="close-layer"></div>');
                    $layer.css('height',main_panel_height + 'px');
                    $layer.appendTo(".main-panel");

                    setTimeout(function(){
                        $layer.addClass('visible');
                    }, 100);

                    $layer.click(function() {
                        $('html').removeClass('nav-open');
                        mobile_menu_visible = 0;

                        $layer.removeClass('visible');

                         setTimeout(function(){
                            $layer.remove();
                            $toggle.removeClass('toggled');

                         }, 400);
                    });

                    $('html').addClass('nav-open');
                    mobile_menu_visible = 1;

                }
            });

            toggle_initialized = true;
        }
    }, 500),


    initBootstrapNavbarMenu: debounce(function(){

        if(!bootstrap_nav_initialized){
            $navbar = $('nav').find('.navbar-collapse').first().clone(true);

            nav_content = '';
            mobile_menu_content = '';

            //add the content from the regular header to the mobile menu
            $navbar.children('ul').each(function(){
                content_buff = $(this).html();
                nav_content = nav_content + content_buff;
            });

            nav_content = '<ul class="nav nav-mobile-menu">' + nav_content + '</ul>';

            $navbar.html(nav_content);
            $navbar.addClass('off-canvas-sidebar');

            // append it to the body, so it will come from the right side of the screen
            $('body').append($navbar);

            $toggle = $('.navbar-toggle');

            $navbar.find('a').removeClass('btn btn-round btn-default');
            $navbar.find('button').removeClass('btn-round btn-fill btn-info btn-primary btn-success btn-danger btn-warning btn-neutral');
            $navbar.find('button').addClass('btn-simple btn-block');

            $toggle.click(function (){
                if(mobile_menu_visible == 1) {
                    $('html').removeClass('nav-open');

                    $('.close-layer').remove();
                    setTimeout(function(){
                        $toggle.removeClass('toggled');
                    }, 400);

                    mobile_menu_visible = 0;
                } else {
                    setTimeout(function(){
                        $toggle.addClass('toggled');
                    }, 430);

                    $layer = $('<div class="close-layer"></div>');
                    $layer.appendTo(".wrapper-full-page");

                    setTimeout(function(){
                        $layer.addClass('visible');
                    }, 100);


                    $layer.click(function() {
                        $('html').removeClass('nav-open');
                        mobile_menu_visible = 0;

                        $layer.removeClass('visible');

                         setTimeout(function(){
                            $layer.remove();
                            $toggle.removeClass('toggled');

                         }, 400);
                    });

                    $('html').addClass('nav-open');
                    mobile_menu_visible = 1;

                }

            });
            bootstrap_nav_initialized = true;
        }
    }, 500),

    startAnimationForLineChart: function(chart){

        chart.on('draw', function(data) {
          if(data.type === 'line' || data.type === 'area') {
            data.element.animate({
              d: {
                begin: 600,
                dur: 700,
                from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                to: data.path.clone().stringify(),
                easing: Chartist.Svg.Easing.easeOutQuint
              }
            });
          } else if(data.type === 'point') {
                seq++;
                data.element.animate({
                  opacity: {
                    begin: seq * delays,
                    dur: durations,
                    from: 0,
                    to: 1,
                    easing: 'ease'
                  }
                });
            }
        });

        seq = 0;
    },
    startAnimationForBarChart: function(chart){

        chart.on('draw', function(data) {
          if(data.type === 'bar'){
              seq2++;
              data.element.animate({
                opacity: {
                  begin: seq2 * delays2,
                  dur: durations2,
                  from: 0,
                  to: 1,
                  easing: 'ease'
                }
              });
          }
        });

        seq2 = 0;
    }
}


// Returns a function, that, as long as it continues to be invoked, will not
// be triggered. The function will be called after it stops being called for
// N milliseconds. If `immediate` is passed, trigger the function on the
// leading edge, instead of the trailing.

function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		clearTimeout(timeout);
		timeout = setTimeout(function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		}, wait);
		if (immediate && !timeout) func.apply(context, args);
	};
};

<%end%>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul>
							<li>
								<%= link_to(root_path)do %>
			                        <p>Home</p>
							    <%end%>
							</li>
							<li>
								<%= link_to(root_path)do %>
			                        <p>Blog</p>
							    <%end%>
							</li>
							<li>
								<%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete %>
							</li>
						</ul>
					</nav>
				</div>
			</footer>
		</div>
	</div>

app/views/layouts/_menu.html.erb
<%
@notificacion = User.where(active: false).count('active')
%>

<div class="wrapper">

	    <div class="sidebar" data-color="red" data-image="/assets/BannerTulua.jpg">
			<div class="logo">
				<a href="#" class="simple-text">
					Campus Virtual
				</a>
			</div>

	    	<div class="sidebar-wrapper">
	            <ul class="nav">
	                <li class="active">
						<%= link_to(root_path)do %>
	                        <%= fa_icon "home"%>
	                        <p>Home</p>
					    <%end%>
	                </li >
	                <li>
	                	<%= link_to(activate_user_path(current_user.id))  do %>
	                        <%= fa_icon "user"%>
	                        <p>Mi Perfil</p>
					    <%end%>
	                </li>

	                <%if current_user.rol==2 %>
		                <li>
		                	<%= link_to(course_users_path)  do %>
		                        <%= fa_icon "clipboard"%>
		                        <p>Cursos</p>
						    <%end%>
		                </li>
	                <%end%>

	                <%if current_user.rol==1 %>
		                <li class="dropdown">	    
		                	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                		<%= fa_icon "address-book-o"%>
								<span class="notification">Cursos</span>
								<b class="caret"></b>
						    </a>
			    			<ul class="dropdown-menu">
							  <li>
							  	<%= link_to(courses_path)  do %>
							  	<%= fa_icon "book"%>
								<span class="notification">Consultar Cursos</span>
						    	<%end%>
						      </li>				
							  <li class="divider"></li>
							  <li>
							  	<%= link_to(new_course_path) do %>
		                        <%= fa_icon "pencil-square-o"%>
								<span class="notification">Crear Cursos</span>
						    	<%end%>
			    			</ul>
		                </li>
	                <%end%>



	                <%if current_user.rol==1 %>
		                <li class="dropdown">	    
		                	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="material-icons">border_color</i>
								<span class="notification">Noticias</span>
								<b class="caret"></b>
						    </a>
			    			<ul class="dropdown-menu">
							  <li>
							  	<%= link_to(reports_path)  do %>
		                        <i class="material-icons">search</i>
								<span class="notification">Consultar Noticias</span>
						    	<%end%>
						      </li>				
							  <li class="divider"></li>
							  <li>
							  	<%= link_to(new_report_path)  do %>
		                        <i class="material-icons">create_new_folder</i>
								<span class="notification">Crear Noticias</span>
						    	<%end%>
			    			</ul>
		                </li>
	                <%end%>
	              
	                <li class="dropdown">	    
	                	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                		<%= fa_icon "book"%>
							<span class="notification">Blog</span>
							<b class="caret"></b>
					    </a>
		    			<ul class="dropdown-menu">
						  <li>
						  	<%= link_to(blogs_path)  do %>
						  	<%= fa_icon "newspaper-o"%>
							<span class="notification">Consultar Blogs</span>
					    	<%end%>
					      </li>				
						  <li class="divider"></li>
						  <li>
						  	<%= link_to(new_blog_path) do %>
	                        <%= fa_icon "clipboard"%>
							<span class="notification">Crear Blog</span>
					    	<%end%>
		    			</ul>
	                </li>

	                <%if current_user.rol==1 %>
		                <li>
		                	<%= link_to(activate_user_index_path)  do %>
		                        <%= fa_icon "user"%>
		                        <p>Activar usuarios</p>
						    <%end%>
		                </li>
		            <%end%>	   
	    	</div>
	    </div>

	    <div class="main-panel">
			<nav class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand"><p> Usuario: <%=current_user.name%> </p></a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<%if current_user.rol==1 %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<%= fa_icon "bell lg"%>
									<%if @notificacion > 0%>
										<span class="notification"><%= @notificacion%></span>
									<%else%>
									<%end%>
									<p class="hidden-lg hidden-md">Notificaciones</p>
								</a>
								<ul class="dropdown-menu">
									<li>
									<%= link_to(activate_user_index_path)  do %>
				                        <%= fa_icon "user"%>
				                        <%= @notificacion%> Usuarios por Activar
								    <%end%></li>									
								</ul>
							</li>
							<%end%>
							<li class="hidden-sm hidden-xs">
			                	<%= link_to(root_path)  do %>
			                        <%= image_tag current_user.avatar.url(:peque)%>
			                        <p class="hidden-lg hidden-md hidden-sm">Mi perfil</p>
							    <%end%>
							</li>
							<li>
								<%= link_to( destroy_user_session_path, :method => :delete )do%>
			                        <%= fa_icon "times"%>
			                        <p class="hidden-lg hidden-md">Cerrar Sesión</p>
								<%end%>
							</li>
						</ul>
						<!--
						<form class="navbar-form navbar-right" role="search">
							<div class="form-group  is-empty">
								<input type="text" class="form-control" placeholder="Search">
								<span class="material-input"></span>
							</div>
							<button type="submit" class="btn btn-white btn-round btn-just-icon">
								<i class="material-icons">search</i><div class="ripple-container"></div>
							</button>
						</form>
						-->
					</div>
				</div>
			</nav>
			<div class="row hidden">
				<% if notice %>
					<p class="alert alert-success" id="notice"><%= notice %></p>
				<% end %>
				<% if alert %>
				  <p class="alert alert-danger" id="alert"><%= alert %></p>
				<% end %>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Campus</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  </head>
<body>
    <%= yield %>
</body>
	<!--<script type="text/javascript">
    	$(document).ready(function(){

			// Javascript method's body can be found in assets/js/demos.js
        	demo.initDashboardPageCharts();

    	});
	</script>-->
</html>